### ISSUE TITLE
Ideas for visualisation

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19#1]
We can use this issue to discuss how the dashboard/GUI will look like. Some initial thoughts discussed with Kellyn on the 16th November:

## Use an interactive map where we can select the country to show the natural/conterfactual history?

An example could be what is shown here:

https://medium.com/datalab-log/how-to-build-a-dashboard-prototype-using-leaflet-d3-js-and-python-1cfda38efbb5

Some questions to think about:

- Do we want to give an interactive option for the user to decide where to build the counterfactual history (eg. the user could select a lockdown happening 3 days before instead of a fixed 7 days?)
- Should the landing map show some information (eg. colour of country is the number of total deaths observed?)
- What to show when clicking on the country (natural history, counterfactual history, general statistics of the country)?

**Comment by crangelsmith** [comment]
Another nice idea for visualisation https://livingatlas.arcgis.com/covidpulse/#@=-94.464,40.252,4&q=46&grid=0

**Comment by jemrobinson** [comment]
Some thoughts about whether to use a front-end framework https://stackoverflow.blog/2020/02/03/is-it-time-for-a-front-end-framework/ (personally I think we probably should unless we are going to keep things extremely simple).

- Looks like [React + Leaflet](https://www.smashingmagazine.com/2020/02/javascript-maps-react-leaflet/) might be a natural combination?

**Comment by crangelsmith** [comment]
Some thoughts in the reading i've done today:

- I looked up to [folium](https://github.com/python-visualization/folium) which is the python implementation of leaflet, although python is our preferred language it felt too limited to what we want to do, also it is not obvious to my how we can be iterative in several layers, and trigger calculations. So my conclusion was that we should go directly to Leaflet that is much more developed. And as @jemrobinson mentioned, can be combined with a front-end framework.
- I was worrying that Leaflet does not have sparklines options as markers, but after reading [this blog](https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/how-to-create-a-sparkline-map-with-the-arcgis-api-for-javascript/) post from the authors of the dashboard that we are using for inspiration, I think we could build them ourselves with a function that turns the lines into restricted coordinates that can be turned into lines. 

Also, this website can be interesting https://dataviz.cafe/
