### ISSUE TITLE
Add a cases histogram to the frontend

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/CounterfactualCovid19#28]
The frontend needs some sort of React component which can display an interactive histogram of cases.

Some possible options for components [are here](https://dev.to/giteden/top-5-react-chart-libraries-for-2020-1amb)

## Prerequisites
- [ ] depends on #32

**Comment by crangelsmith** [comment]
Rechart seems like like the easiest option (https://recharts.org/en-US/examples)

Also, I found this project where they mix Rechart and Leaflet and that could give us an example of how to start: https://github.com/tyreer/robs-hack-oregon-library

**Comment by crangelsmith** [comment]
These might be relevant (just to prove that pop-up charts are possible): 

https://stackoverflow.com/questions/59213888/how-to-arrange-graphics-using-css-two-by-two-in-reactjs
https://stackoverflow.com/questions/59196857/how-to-style-leaflet-popup-width-and-h%D0%B5ight-on-reactjs
