### ISSUE TITLE
Ideas for backend of dashboard. 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19#3]
Notes from meeting on 16th November:

- The code that estimates the best not points for each country stays in R repository, data gets added to this repo.
- This repo will read not points, case data and will run the natural history and counterfactual analysis. 
- First step try to reproduce results from UK.

@KFArnold we can use this issue to discuss the general backend ideas.

**Comment by KFArnold** [comment]
Have created repository KFArnold/CounterfactualCovid19-inputs (https://github.com/KFArnold/CounterfactualCovid19-inputs) and committed initial scripts for summarising, finding best knot points, and simulating counterfactuals.

**Comment by jemrobinson** [comment]
If we're talking about a [web backend](https://github.com/gothinkster/realworld) here, then probably Django would be the best for us since @crangelsmith and @jemrobinson are probably most comfortable with Python.
