### ISSUE TITLE
Front end design

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19#41]
### Colour key:
- [ ] Use one of the colorbrewer.org sets eg. `['#ffffcc','#a1dab4','#41b6c4','#2c7fb8','#253494']`

### Legend
- [ ] Make narrower but leave as a separate component

### About
- [ ] Add some info about the project (eg. as a pop-up box)

### Country highlighter
- [ ] [Add a border highlight](47) (like this one https://leafletjs.com/examples/choropleth/)
- [ ] Remove the pop-up marker

#### in default view
- [ ] Keep the "Select a country" text
- [ ] Change the colour from grey to something else

#### in selected country view
- [ ] Total number of cases
- [ ] A date-range selector (like the kayak one below?) which lets you pick the first-restrictions/lockdown dates
- [ ] Left-hand info box:
  - [ ] real sum(cases)
  - [ ] counterfactual sum(cases)
- [ ] Histogram to show
  - [ ] daily real cases (bars)
  - [ ] daily counterfactual cases (line)

**Comment by crangelsmith** [comment]
<img width="686" alt="Screenshot 2021-02-01 at 15 44 15" src="https://user-images.githubusercontent.com/11162074/106481668-90b30e80-64a4-11eb-8790-8dc03f11069c.png">

**Comment by crangelsmith** [comment]
Resulting sketch from our meeting on 1st Feb:

<img width="1058" alt="Screenshot 2021-02-01 at 16 10 22" src="https://user-images.githubusercontent.com/11162074/106485143-3320c100-64a8-11eb-8deb-29225cf0c0a6.png">
<img width="1077" alt="Screenshot 2021-02-01 at 16 11 21" src="https://user-images.githubusercontent.com/11162074/106485172-3b78fc00-64a8-11eb-93c1-b55727147531.png">

**Comment by crangelsmith** [comment]
Update:

@crangelsmith to start working on the landing page in a new PR.

**Comment by jemrobinson** [comment]
@crangelsmith: Hopefully split across multiple PRs, right? :)

**Comment by crangelsmith** [comment]
Link to the design: https://wireframepro.mockflow.com/view/M8566547bdab53b42542d09b05bae40421612188126292
