### ISSUE TITLE
"About the project" text

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19#46]
Currently we have a placeholder with an "About the project" information, we need to eventually update it with actual text.

@KFArnold, when you have a draft of this text you can write it as a comment to this issue (but no pressure, i'm writing this issue to make sure we don't forget).

**Comment by KFArnold** [comment]
Hi @crangelsmith - Here's a draft of the 'About the project' text. Mark has signed off on it, but I'm happy if you want to make any changes/additions/clarifications!

This is a joint project between the Leeds Institute for Data Analytics at the University of Leeds and the Alan Turing Institute (grant number EP/N510129/1). This project aims to assess the effects of lockdown timing on the growth of COVID-19 cases across Europe during the first wave. Analytical code and documentation relating to this project can be found at https://github.com/KFArnold/covid-lockdown/; source code and documentation for this dashboard can be found at https://github.com/alan-turing-institute/CounterfactualCovid19.

Note that countries are coloured on the map according to the number of COVID-19 cases per million recorded as of 6 July 2020.
