### ISSUE TITLE
How connected (conceptually) is `PossibleDates` with `Dates`? Could/should they be two models living in the same module?

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19#56]
How connected (conceptually) is `PossibleDates` with `Dates`? Could/should they be two models living in the same module?

_Originally posted by @jemrobinson in https://github.com/alan-turing-institute/CounterfactualCovid19/pull/52#discussion_r590482782_

**Comment by jemrobinson** [comment]
Closed by #58.
