### ISSUE TITLE
TypeError at /api/cases/counterfactual/daily/absolute/

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/CounterfactualCovid19#69]
Issue with API call for /api/cases/counterfactual/daily/absolute/

```
Internal Server Error: /api/cases/counterfactual/daily/absolute/
backend_1   | Traceback (most recent call last):
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
backend_1   |     response = get_response(request)
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
backend_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
backend_1   |     return view_func(*args, **kwargs)
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
backend_1   |     return self.dispatch(request, *args, **kwargs)
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
backend_1   |     response = self.handle_exception(exc)
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
backend_1   |     self.raise_uncaught_exception(exc)
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
backend_1   |     raise exc
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
backend_1   |     response = handler(request, *args, **kwargs)
backend_1   |   File "/app/backend/cases/views.py", line 46, in list
backend_1   |     return Response(serializer.data)  # pylint: disable=no-member
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
backend_1   |     ret = super().data
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
backend_1   |     self._data = self.to_representation(self.instance)
backend_1   |   File "/root/.cache/pypoetry/virtualenvs/counterfactualcovid19-vsmFjuTQ-py3.9/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
backend_1   |     return [
backend_1   | TypeError: 'type' object is not iterable
```

**Comment by crangelsmith** [comment]
This error is caused by [this line](https://github.com/alan-turing-institute/CounterfactualCovid19/blob/fd391c7d9172a5ed24b286220086cd6b9fb75ad0/backend/cases/views.py#L57) where no simulation is run for the absolute daily cases. Is this intended @jemrobinson?

**Comment by jemrobinson** [comment]
I think it's literally not implemented yet (ie. we haven't done the normalise-by-population step anywhere). We'd need to add the code to do this to one or more of `CounterfactualCasesRecord` and `simulation.py`

**Comment by crangelsmith** [comment]
> I think it's literally not implemented yet (ie. we haven't done the normalise-by-population step anywhere). We'd need to add the code to do this to one or more of `CounterfactualCasesRecord` and `simulation.py`

I think the normalisation is done in [here](https://github.com/alan-turing-institute/CounterfactualCovid19/blob/fd391c7d9172a5ed24b286220086cd6b9fb75ad0/backend/cases/serializers/ephemeral.py#L26)? 

In fact, if I replace [it](https://github.com/alan-turing-institute/CounterfactualCovid19/blob/fd391c7d9172a5ed24b286220086cd6b9fb75ad0/backend/cases/views.py#L57) with  the line:
```
return CounterfactualCasesRecord.simulate(
            iso_codes, boundary_dates, knot_dates, summary=False
        )
```

the problem is fixed, and the values are X times larger than the normalised stream.

**Comment by crangelsmith** [comment]
> > I think it's literally not implemented yet (ie. we haven't done the normalise-by-population step anywhere). We'd need to add the code to do this to one or more of `CounterfactualCasesRecord` and `simulation.py`
> 
> I think the normalisation is done in [here](https://github.com/alan-turing-institute/CounterfactualCovid19/blob/fd391c7d9172a5ed24b286220086cd6b9fb75ad0/backend/cases/serializers/ephemeral.py#L26)?
> 
> In fact, if I replace [it](https://github.com/alan-turing-institute/CounterfactualCovid19/blob/fd391c7d9172a5ed24b286220086cd6b9fb75ad0/backend/cases/views.py#L57) with the line:
> 
> ```
> return CounterfactualCasesRecord.simulate(
>             iso_codes, boundary_dates, knot_dates, summary=False
>         )
> ```
> 
> and the values are X times larger than the normalised stream.

Oh no, this is not true. I made a mistake in my comparison,  both values are the same....

**Comment by crangelsmith** [comment]
> and the values are X times larger than the normalised stream.

Last edit to this comment (i think this is my cue that i should stop working for today), the counterfactual normalisation does work:
e.g.

From: http://localhost:8000/api/cases/counterfactual/daily/normalised/
```

{
        "iso_code": "ALB",
        "date": "2020-03-12",
        "weekly_avg_cases_per_million": 1.9566521490855486,
        "summed_avg_cases_per_million": 7.863054348517892
    },

```
From: http://localhost:8000/api/cases/counterfactual/daily/absolute/

```
 {
        "iso_code": "ALB",
        "date": "2020-03-12",
        "weekly_avg_cases": 5.5846589540506315,
        "summed_avg_cases": 22.442658954050632
    },
```
